name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flower-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flower-frontend:latest ./frontend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flower-backend:latest

      - name: Trigger Azure backend update
        run: |
          curl -u '${{ secrets.AZURE_WEBHOOK_USER }}:${{ secrets.AZURE_WEBHOOK_PASS }}' \
          -X POST 'https://flower-backend-ahmad-eeg8aqg8fkhndvfe.scm.francecentral-01.azurewebsites.net/api/registry/webhook'

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flower-frontend:latest

      - name: Trigger Azure frontend update
        run: |
          curl -u '${{ secrets.AZURE_WEBHOOK_USER_FRONT }}:${{ secrets.AZURE_WEBHOOK_PASS_FRONT }}' \
          -X POST 'https://YOUR-FRONTEND-SCM-URL/api/registry/webhook'